### ISSUE TITLE
refresh the token manually

### ISSUE THREAD

**Issue by Passive1** [googlesamples/apps-script-oauth2#10]
Salesforce does not provide any expiration values in its response, sample provided, 

 {"id":"https://login.salesforce.com/id/00Dx0000000BV7z/005x00000012Q9P",
"issued_at":"1278448101416","refresh_token":"5Aep8614iLM.Dq661ePDmPEgaAW9
Oh_L3JKkDpB4xReb54_pZebnUG0h6Sb4KUVDpNtWEofWM39yg==","instance_url":
"https://na1.salesforce.com","signature":"CMJ4l+CCaPQiKjoOEwEig9H4wqhpuLSk
4J2urAe+fVg=","access_token":"00Dx0000000BV7z!AR8AQP0jITN80ESEsj5EbaZTFG0R
NBaT1cyWk7TrqoDjoNIWQ2ME_sTZzBjfmOE6zMHq6y8PIW4eWze9JksNEkWUl.Cju7m4","token_type":"Bearer","scope":"id api refresh_token"}

so refreshing needs to be handled externally.  Your refresh function is private.  Can you set this up so the token can be refreshed manually.

**Comment by erickoledadevrel** [comment]
The refresh() method is now public.
