### ISSUE TITLE
Fitbit OAuth2.0

### ISSUE THREAD

**Issue by simonbromberg** [googlesamples/apps-script-oauth2#12]
Got pretty far trying to implement this for Fitbit's OAuth2.0, but stuck on this error:

    Error retrieving token: 400 (line 262, file "Service", project "OAuth2")

What does that error code mean in this context?  Any suggestions as to what I might be doing wrong? Or is it a problem with the compatibility of the Fitbit API?

Through debugging, it looks like it doesn't get past this line in `authCallback`

    var isAuthorized = service.handleCallback(request);

**Comment by erickoledadevrel** [comment]
The FitBit OAuth2 flow requires that you pass an extra header when making token requests. Use the new setTokenHeaders() method to add the header:

function getFitbitService() {
      var clientId = '...';
      var clientSecret = '...;
      return OAuth2.createService('fitbit')
          .setAuthorizationBaseUrl('https://www.fitbit.com/oauth2/authorize')
          .setTokenUrl('https://api.fitbit.com/oauth2/token')
          .setClientId(clientId)
          .setClientSecret(clientSecret)
          .setProjectKey('...')
          .setCallbackFunction('authCallback')
          .setPropertyStore(PropertiesService.getUserProperties())
          .setScope('activity')
          .setTokenHeaders({
            'Authorization': 'Basic ' + Utilities.base64Encode(clientId + ':' + clientSecret)
          });
    }

**Comment by simonbromberg** [comment]
Wow, thanks!
