### ISSUE TITLE
Switch to new user account within same sheet

### ISSUE THREAD

**Issue by simonbromberg** [googlesamples/apps-script-oauth2#13]
I have multiple accounts I want to authorize, one at a time, downloading data from one and then switching to another. Previously with OAuth1 I did this by changing the service identifier, but that doesn't seem to be working anymore. It just remembers the authorization from before. I also tried running the reset shown in the readme before switching, but that didn't seem to do anything either. I also tried logging out of the first account in my browser, and then when authorizing I logged into the second account, and I got to the authorization page, but it said "400 Bad request Your browser sent an invalid request."

(This is for the Fitbit API)

Is there a way to do this, or do I have to make a separate sheet for each one?

**Comment by techstreams** [comment]
Are you setting the cache on the service object using *.setCache()*?

If so, [reset()](https://github.com/googlesamples/apps-script-oauth2/blob/ref/heads/master/Service.gs#L311) is not clearing the cache when the property store is reset for the service. This *might* be causing [getToken_()](https://github.com/googlesamples/apps-script-oauth2/blob/ref/heads/master/Service.gs#L409) to retrieve an old token from the cache before the cache expiration.

**Comment by simonbromberg** [comment]
No, I don't think so. 

Here's where I create the service

    function getFitbitService() { 
    return OAuth2.createService(SERVICE_IDENTIFIER)

      .setAuthorizationBaseUrl('https://www.fitbit.com/oauth2/authorize')
      .setTokenUrl('https://api.fitbit.com/oauth2/token')

      .setClientId(CONSUMER_KEY)
      .setClientSecret(CONSUMER_SECRET)

      .setCallbackFunction('authCallback')

      .setPropertyStore(PropertiesService.getUserProperties())

      .setScope('activity')
      .setParam('redirect_uri','https://script.google.com/macros/d/'+PROJECT_KEY+'/usercallback')
      .setTokenHeaders({
        'Authorization': 'Basic ' + Utilities.base64Encode(CONSUMER_KEY + ':' + CONSUMER_SECRET)
      });
    }

**Comment by erickoledadevrel** [comment]
You should be able to accomplish this by creating services with different names. Please double check your code.

**Comment by simonbromberg** [comment]
Hm, now changing the SERVICE_IDENTIFIER above seems to be working, like you said; Weird, didn't change anything. Thanks!

**Comment by simonbromberg** [comment]
Oh, seemed to work when I used an account I previously authorized on its own in a separate sheet, but when I tried a new account that I hadn't authorized before (i.e. showed the Deny/Allow page after login) I got the "400 Bad request"

(note all these accounts have been authorized before in a separate sheet for the same application credentials, although I suppose that doesn't matter since that was OAuth1 and the OAuth2 has a different client ID)
