### ISSUE TITLE
Access to the ‘Picasa Web Albums Data API’

### ISSUE THREAD

**Issue by actermeer** [googlesamples/apps-script-oauth2#14]
I have container bound (Sheet) Google Apps scripts to retrieve information from my Picasa web albums. These scripts use the ‘Picasa Web Albums Data API’. 
Since April 20th, 2015 OAuth2.0 is the one and only way to authorize requests for the Picasa API. So my scripts do not work anymore. I would like to use the ‘OAuth2 for Apps Script’ library for autorisation.

I extended the libraries example Apps script to access the Picasa API:
- Added a new function reqPicasa(). Which is a copy of the original makeRequest(), but using an URL for Picasa; ’https://picasaweb.google.com/data/feed/api/user/default'. When logged in into Gmail this URL supplies a XML feed about your Picasa web albums.
- Extended the scope in getDriveService() with ‘https://picasaweb.google.com/data’.

The Developers Console does not list the ‘Picasa Web Albums Data API’. According to the Developer's Guide: Protocol for Picasa (chapter Authorizing requests) enabling that API can be skipped when creating the Client ID. 

Results:
Calling the makeRequest() gives an excellent list of my Drive. So there is an working example.
However calling reqPicasa() only gives: ‘Request failed for https://picasaweb.google.com/data/feed/api/user/default returned code 403. Truncated server response: Token invalid - AuthSub token has wrong scope (use muteHttpExceptions option to examine full response).’

I did not find a solution to the autorisation problem for Picasa. Hope you can help to get my script up and running again.

**Comment by erickoledadevrel** [comment]
The problem is most likely that you had previously retrieved a token with only the Drive scope, and so when you added the Picasa scope it was ignored because the stored token was used. Use Service.reset() to rest your authorizations and then try again.

**Comment by actermeer** [comment]
Yes, that was the solution.
Thanks!
