### ISSUE TITLE
How can i retrieve the other data sent along with access_token response

### ISSUE THREAD

**Issue by wpgeek922** [googlesamples/apps-script-oauth2#15]
The getAuthorizationUrl() function return only access token, I want to retrieve the data sent along with the access_token e.g. blog id and save it with user properties. How can i achieve this?

**Comment by erickoledadevrel** [comment]
getAuthorizationUrl() returns a URL. The handleCallback() method does the final exchange of the tokens. All of the data is saved, and you can use the "private" method Service.getToken_() to retrieve the full token that was returned by the server, including any extra information.
