### ISSUE TITLE
Enable in Scripts

### ISSUE THREAD

**Issue by kasparov** [googlesamples/apps-script-oauth2#17]
When writing a script (no UI), there is no way to present the user with the button UI to click Authorize. Investigate if there is a way to trigger an Authorization flow similar to accessing Google's built-in services.

**Comment by erickoledadevrel** [comment]
There is no way to trigger a dialog from the script editor, and it's not something that will likely be built. One solution is to throw an exception that asks the user to authorize and includes the URL.
