### ISSUE TITLE
Empty JSON Error

### ISSUE THREAD

**Issue by wpgeek922** [googlesamples/apps-script-oauth2#18]
This is the error i get :
Token response not valid JSON: SyntaxError: Empty JSON string (line 330, file "Service", project "OAuth2")

**Comment by erickoledadevrel** [comment]
What provider/API are you authorizing against?

**Comment by wpgeek922** [comment]
Hi Eric,

I'm working with WordPress REST API.

You can check my application here
<https://chrome.google.com/webstore/detail/publish-to-wordpress/lllekagcmcimoimdjlchepfokgengccb>
.

Thanks & Regards
Mohammed Imtiyaz
+91 9000909218

**Comment by erickoledadevrel** [comment]
It looks like the Wordpress OAuth2 endpoint is not returning valid JSON. Did this just start happening? I can make the library better handle missing JSON, but it still won't resolve the underlying issue that's causing it.

**Comment by erickoledadevrel** [comment]
I was able to get Wordpress working and added a sample: https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/Wordpress.gs
