### ISSUE TITLE
Error refreshing token: invalid_grant

### ISSUE THREAD

**Issue by St3ph-fr** [googlesamples/apps-script-oauth2#19]
Hi

Description of issue :
I created an addon and using oauth2 lib.
At first connection user grant permission for addon
Addon display link to grant oauth2 access.
User validate access, and re open addon. 
Access is granted and user can use addon.
User go in his account and revoke access for the add-on.
User open again addon, permission pop up for addon appears
User validate permission.
After validation user get issue : Error refreshing token: invalid_grant
Now each time user try to open addon he get this error.

Details of error : Error refreshing token: invalid_grant (line 379, file "Service", project "OAuth2")

Way to solve the issue : Have access to the script and run PropertiesService.getUserProperties().deleteAllProperties()

After deleting all properties issue above is not displayed.

In the function which open the sidebar for addon I try to catch this error but does not work. I do 
 try{
      var service = getService();
}catch(e){
      .....
}

I use version 13 of the lib.
Scope of oauth 2 : http://www.google.com/m8/feeds/
Code of lib is too complex for me so I can't give be more helpful.

Stéphane

**Comment by St3ph-fr** [comment]
I'm sorry but does not work properly. I no longer get the error message but nothing happens. I tested and from hasaccess I received a true.

As a quick fix I will test token by myself.
try{
var fetch = UrlFetchApp.fetch("https://www.googleapis.com/oauth2/v1/tokeninfo?access_token="+TOKEN);
     }catch(e){
       PropertiesService.getUserProperties().deleteAllProperties();
     }

May that can help you ?
After this try/catch I use the hasaccess.

Stéphane

**Comment by erickoledadevrel** [comment]
Can you provide a more detailed set of steps and sample code that I can use to replicate the problem?

**Comment by St3ph-fr** [comment]
Basically it is what I do and don't get a false.

var service = getSharedService();
if (!service.hasAccess()) {
      Display screen with authorization url.
    } else {
      Display app screen
    }

hasAccess() send me a true so I don't display the screen with authorization url.

**Comment by erickoledadevrel** [comment]
My fix only makes it so that errors during token refresh return false. If the access token isn't expired but was revoked, there is no way to determine that without making a request (either to the API itself of the token validation endpoint). My guess is that your request to the API is returning an error response (like 403 or 401) and you should catch that error and re-show the authorization prompt. That is not something the library can handle for you, as the process varies from API to API.

**Comment by St3ph-fr** [comment]
OK so I will keep this check before to display user interface
Thank you for support.

Stéphane
