### ISSUE TITLE
Token Expired

### ISSUE THREAD

**Issue by miguelperezcw** [googlesamples/apps-script-oauth2#20]
Hi, 

Had been using the library correctly but when upgrading to version 14 have some errors Access not granted or expired. (line 306, file "Service").

Run again manually access and work but after a while it gets to fall, this did not happen with version 10.

Regards.

**Comment by erickoledadevrel** [comment]
Which API are you authorizing against? How long until it fails again?

**Comment by miguelperezcw** [comment]
Hi Eric, 

I'm using reseller API. Every time I make authentication begins to fail after about 1 hour.

**Comment by erickoledadevrel** [comment]
Are you requesting offline access? If not you won't get a refresh token, and therefore won't be able to refresh the access token when it expires.

**Comment by miguelperezcw** [comment]
Yes

This is my code, the parameters are sent when I call this function.

function getResellerOAuth(clientId, clientSecret, projectKey, efectiveUser, scopes) { 
  return OAuth2.createService('customers')     
      .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
      .setTokenUrl('https://accounts.google.com/o/oauth2/token')    
      .setClientId(clientId)
      .setClientSecret(clientSecret)    
      .setProjectKey(projectKey)    
      .setCallbackFunction('authCallback')
      .setPropertyStore(PropertiesService.getUserProperties())
      .setScope(scopes)     
      .setParam('login_hint', efectiveUser)    
      .setParam('access_type', 'offline')     
     // .setParam('approval_prompt', 'force');
}

**Comment by erickoledadevrel** [comment]
Did you ever reset the service / clear your use properties? Google only returns the refresh token the first time you authorize the service, so if it was lost then it won't be restored in future authorizations.

Try revoking access for this script / project and reauthorizing.

**Comment by miguelperezcw** [comment]
I have revoked all access and then I generated the license again far it works, I'll wait a while and see if it does not expire again.

Once you give permission not remove access to the application. I guess with this permission Google refresh the token.

**Comment by miguelperezcw** [comment]
Thanks a lot Eric !!

The script no longer fails expired permits.

Nice to talk to you.
You have a good day.
