### ISSUE TITLE
callback function is not firing

### ISSUE THREAD

**Issue by Kaushick** [googlesamples/apps-script-oauth2#21]
Using this library for linkedIn authorization. Here is my code snippet:

    // This is the service
    function getLinkedInService() {
  
     var service = OAuth2.createService('linkedIn')
      service.setAuthorizationBaseUrl('https://www.linkedin.com/uas/oauth/authorize')
      service.setTokenUrl('https://api.linkedin.com/uas/oauth/accessToken')
      service.setClientId(clientId)
      service.setClientSecret(clientSecret)
      service.setCallbackFunction('auth2Callback')
      service.setPropertyStore(PropertiesService.getUserProperties())
      service.setScope(['r_basicprofile','r_emailaddress','rw_company_admin','w_share'])
      
      return service; 
    }

    // This is the callback function
    function auth2Callback(request) {
         Logger.log('in oauth 2 callback => ' + request);
         var linkedInService = getLinkedInService();
        var isAuthorized = linkedInService.handleCallback(request);
        if (isAuthorized) {
        return HtmlService.createHtmlOutput('Success!');
      } else {
         return HtmlService.createHtmlOutput('Denied.');
      }
    }

       // This is the function I'm running
        function showSidebar() {
              var linkedInService = getLinkedInService();
              if (!linkedInService.hasAccess()) {
                   var authorizationUrl = linkedInService.getAuthorizationUrl();
                   // Getting a proper url here
                   // If I put this url in a browser it is redirecting in my redirect_uri
                   // Also getting the token here.
             } else {
                  makeRequest(); // This function calls the api.
             }
         } 

Now, the problems I 'm facing are:

1. When the callback function will fire?
2. Is there a way to automate the process of getting access_token from "authorizationUrl"?

**Comment by erickoledadevrel** [comment]
I've published a complete LinkedIn sample here:

https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/LinkedIn.gs

The callback fires after the user clicks "Authorize", and will show the "Success" message. There is no way to automate the process; this OAuth2 flow requires for human interaction.

**Comment by Kaushick** [comment]
Thank You for your response. When I'm opening the "authorizationUrl" in a new tab; getting an error "An Authorization Token was not supplied"

Can you tell me the reason? Am I doing wrong?
