### ISSUE TITLE
get rid of Library (underscore)

### ISSUE THREAD

**Issue by yureckey** [googlesamples/apps-script-oauth2#23]
Google apps script Libraries in its current state are somewhat "quirky". As official doc says:
"Warning: A script that uses a library will not run as quickly as it would if all the code were contained within a single script project. Although libraries can make development and maintenance more convenient, you should avoid them in projects where speed is critical. Because of this issue, libraries should not be used in add-ons."
So, in my projects I use oauth2 just as another script file, not Library.
I would like to have all the source in the oauth2 script(s) itself, I mean either include underscore source or not use underscore at all. There are very few functions from underscore that are in use now. For my projects I just ripped them out of underscore, so it's look like this:

//     Underscore.js 1.8.3
//     http://underscorejs.org
//     (c) 2009-2015 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
//     Underscore may be freely distributed under the MIT license.
(function() {
  var root = this;
  
  // Save bytes in the minified (but not gzipped) version:
  var ArrayProto = Array.prototype, ObjProto = Object.prototype, FuncProto = Function.prototype;
  
  // Create quick reference variables for speed access to core prototypes.
  var
  push             = ArrayProto.push,
      slice            = ArrayProto.slice,
      toString         = ObjProto.toString,
      hasOwnProperty   = ObjProto.hasOwnProperty;
  
  // All **ECMAScript 5** native function implementations that we hope to use
  // are declared here.
  var
  nativeIsArray      = Array.isArray,
      nativeKeys         = Object.keys,
      nativeBind         = FuncProto.bind,
      nativeCreate       = Object.create;
  
  // Create a safe reference to the Underscore object for use below.
  var __ = function(obj) {
    if (obj instanceof __) return obj;
    if (!(this instanceof __)) return new __(obj);
    this.__wrapped = obj;
  };
  
  root.__ = __;
  
  var property = function(key) {
    return function(obj) {
      return obj == null ? void 0 : obj[key];
    };
  };
  
  // Helper for collection methods to determine whether a collection
  // should be iterated as an array or as an object
  // Related: http://people.mozilla.org/~jorendorff/es6-draft.html#sec-tolength
  // Avoids a very nasty iOS 8 JIT bug on ARM-64. #2094
  var MAX__ARRAY__INDEX = Math.pow(2, 53) - 1;
  var getLength = property('length');
  var isArrayLike = function(collection) {
    var length = getLength(collection);
    return typeof length == 'number' && length >= 0 && length <= MAX__ARRAY__INDEX;
  };
  
  // Add some isType methods: isArguments, isFunction, isString, isNumber, isDate, isRegExp, isError.
  ['Arguments', 'Function', 'String', 'Number', 'Date', 'RegExp', 'Error'].map(function(name) {
    __['is' + name] = function(obj) {
      return toString.call(obj) === '[object ' + name + ']';
    };
  });
  
  __.isObject = function(obj) {
    var type = typeof obj;
    return type === 'function' || type === 'object' && !!obj;
  };

  // Retrieve the names of an object's own properties.
  // Delegates to **ECMAScript 5**'s native `Object.keys`
  __.keys = function(obj) {
    if (!__.isObject(obj)) return [];
    if (nativeKeys) return nativeKeys(obj);
    //var keys = [];
    //for (var key in obj) if (__.has(obj, key)) keys.push(key);
    // Ahem, IE < 9.
    //if (hasEnumBug) collectNonEnumProps(obj, keys);
    return keys;
  };
  
  // Is a given array, string, or object empty?
  // An "empty" object has no enumerable own-properties.
  __.isEmpty = function(obj) {
    if (obj == null) return true;
    if (isArrayLike(obj) && (__.isArray(obj) || __.isString(obj) || __.isArguments(obj))) return obj.length === 0;
    return __.keys(obj).length === 0;
  };
  
  // Is a given value an array?
  // Delegates to ECMA5's native Array.isArray
  __.isArray = nativeIsArray || function(obj) {
    return toString.call(obj) === '[object Array]';
  };
  
  // An internal function for creating assigner functions.
  var createAssigner = function(keysFunc, undefinedOnly) {
    return function(obj) {
      var length = arguments.length;
      if (length < 2 || obj == null) return obj;
      for (var index = 1; index < length; index++) {
        var source = arguments[index],
            keys = keysFunc(source),
            l = keys.length;
        for (var i = 0; i < l; i++) {
          var key = keys[i];
          if (!undefinedOnly || obj[key] === void 0) obj[key] = source[key];
        }
      }
      return obj;
    };
  };
  
  // Retrieve all the property names of an object.
  __.allKeys = function(obj) {
    if (!__.isObject(obj)) return [];
    var keys = [];
    for (var key in obj) keys.push(key);
    // Ahem, IE < 9.
    //if (hasEnumBug) collectNonEnumProps(obj, keys);
    return keys;
  };
  __.extend = createAssigner(__.allKeys);
    return __;
}.call(this));

**Comment by erickoledadevrel** [comment]
I personally prefer to keep the library, but I have added a new distributable version (in the dist/ directory) that allows you to easy copy and paste two files and not have to deal with Apps Script's library system.
