### ISSUE TITLE
ReferenceError: "OAuth2" is not defined. (line 354, file "")

### ISSUE THREAD

**Issue by BrendonGeils** [googlesamples/apps-script-oauth2#25]
After inputting my Client(consumer) Key, Client(consumer) Secret, and project key into the Configuration Dialog box. I try and run "authorize" and get the error: "ReferenceError: "OAuth2" is not defined. (line 354, file "")."

Am I missing a step? Also in the config dialog box it says "Fitbit OAuth 2.0 Client ID:" should I be entering the "Client ID" or the "Client Key." In the program it refers to this variable as a key, but the dialog box states "Client ID."

**Comment by erickoledadevrel** [comment]
You appear to be using a specific script or add-on, instead of using this library directly. Please contact the creator of the script or add-on for support.

**Comment by CommonRaven** [comment]
Old question. but here's the solution:
You didn't import the Oauth2 library in apps script.
Check out [Setup in the readme](https://github.com/googlesamples/apps-script-oauth2/tree/0e7bcd464962321a75ccb97256d5373b27c4c2e1#setup).

**Comment by SekharChandraK** [comment]
Hi,
I am also facing same problem. Help me 

I am setting the all configurations but still getting that error, and tell me how to execute OAuth2.gs file In return statement I am getting this problem.

Mycode:
function getOAuthService(user) {
    return OAuth2.createService("Service Account")
        .setTokenUrl('https://accounts.google.com/o/oauth2/token')
        .setPrivateKey(JSON.private_key)
        .setIssuer(JSON.client_email)
        .setSubject(JSON.user_email)
        .setPropertyStore(PropertiesService.getScriptProperties())
        .setParam('access_type', 'offline')
        .setScope('https://www.googleapis.com/auth/drive');
        .setScope('https://www.googleapis.com/auth/script.external_request');
        .setScope('https://www.googleapis.com/auth/documents');
        
}

function getUserFiles() {
    var service = getOAuthService();
    service.reset();
    if (service.hasAccess()) {
        var url = 'https://www.googleapis.com/drive/v2/files?pageSize=1';
        var response = UrlFetchApp.fetch(url, {
            headers: {
                Authorization: 'Bearer ' + service.getAccessToken()
            }
        });
        Logger.log(response.getContentText());
        console.log(response.getContentText());
    }
}

function reset() {
    var service = getOAuthService();
    service.reset();
}

**Comment by TheeranMahadev** [comment]
Hi , i am also facing the same issue though i have add my script Id to the library. please give me a suggestion. i don't know what i m doing wrong.

**Comment by Kamlesh480** [comment]
> Old question. but here's the solution: You didn't import the Oauth2 library in apps script. Check out [Setup in the readme](https://github.com/googlesamples/apps-script-oauth2/tree/0e7bcd464962321a75ccb97256d5373b27c4c2e1#setup).

set Oauth2 : https://github.com/googleworkspace/apps-script-oauth2
