### ISSUE TITLE
Service_.prototype.reset doesn't revoke the token

### ISSUE THREAD

**Issue by mihaiaperghis** [googlesamples/apps-script-oauth2#26]
Hi!

I noticed that Service_.prototype.reset only deletes the access token and all other details from the user properties, but doesn't actually revoke the token.

This means that if I have access_type as 'offline' and I use Service_.prototype.reset, I won't receive a new refresh token upon re-authorization. The only way to generate a refresh token is to go in the Google account and manually revoke the app access.

I saw that the [developer docs](https://developers.google.com/youtube/v3/guides/auth/installed-apps#OAuth2_Revoking_a_Token) mention a way to programmatically revoke the token using https://accounts.google.com/o/oauth2/revoke?token={token}

It would be useful to have that included in the reset() function, so that the user can completely remove access and properly re-authorize (and receive a new refresh_token if they need to).

Cheers!

**Comment by erickoledadevrel** [comment]
Unfortunately revoking tokens is not part of the OAuth2 specification, so there is no standard way to do it. Given that this library is a general purpose one, I wouldn't want to hard-code some Google-specific behavior. Given how easy it is to make this request yourself using `UrlFetchApp`, I don't think there is much benefit either.

**Comment by mihaiaperghis** [comment]
I agree, I was under the impression that revoking the tokens was part of the general OAuth2 specification. Since this is a specific scenario, it wouldn't make sense to include it.

I've since used the URL to revoke the token directly in my script, which works perfectly fine, so problem solved :)
