### ISSUE TITLE
OAuth2.gs:getRedirectUri() hard codes the user callback function name

### ISSUE THREAD

**Issue by glawlor** [googlesamples/apps-script-oauth2#30]
There's an error when requesting the authorization url when using  a non-default authorization callback (say 'authCallback') instead of the default 'usercallback'.

Service.gs:Service_.prototype.getAuthorizationUrl() calls OAuth2.gs:getRedirectUri() in order to build the auth url with the buildUrl_() function.

**Comment by erickoledadevrel** [comment]
I'm not sure I understand the issue. Can you provide some rough sample code, or some of the error text returned.

**Comment by glawlor** [comment]
Even when I call OAuth2.setCallbackFunction('authCallback'), the generated authorization url is:

https://github.com/login/oauth/authorize?client_id=NZU6vi2kxYs6tXafgz1jfAZEL&response_type=code&redirect_uri=https%3A%2F%2Fscript.google.com%2Fmacros%2Fd%2FMGMRuex5aul470gPy8k3tVOa_HYPet8-i%2Fusercallback&state=ADEpC8x2nwy_XpgQe6v8DUZuky98c-YhTPIoHp94a6rWJQ-7uSe7jlk8qdyWMzU_ZsEiz7Abm5kvMMjdPwKqtbMwVP7Jspk5ot2ZoaqQriyCK4NfXHENaZxOgsGAuX0bRPOUnaPPCRsI8BOynsVTzwER9EWijUezLx6k_voy1pumUoL0jCjvoWpr6uRLsSQ1r5tHw7va8nRRu8ekayO68c9M3wizW1vByqBcyUfwHCCXionutTKUF96RQajvBfVsqIbf_y8pm55SIiSFGtqQkFt4_6DoUhpZCwZuHtyki__9eTBIftK3Zfs

I guess the parameter 'redirect_uri' should have a value ending in authCallback not usercallback above?

The correct callback function name is encoded in the state token so perhaps this doesn't matter.. the error I was getting wasn't connected to this.
