### ISSUE TITLE
Redirect uri missmatch

### ISSUE THREAD

**Issue by FrenchBen** [googlesamples/apps-script-oauth2#31]
Following this oauth example, I got the following error:
```
The redirect URI in the request: https://script.google.com/macros/d/{PROJECT_ID}/usercallback did not match a registered redirect URI.
```
The project id was properly replaced, yet it failed to be a proper callback.

Using `https://script.google.com/oauthcallback` which was in the client_secret.json worked a bit better, as it gave me the auth approval buttons, but then dies with the following error: `Sorry, the file you have requested does not exist.`

How do I fix this?

ps: the script used was following the quickstart guide:
https://developers.google.com/apps-script/guides/rest/quickstart/go

**Comment by erickoledadevrel** [comment]
The /oauthcallback endpoint is used by Apps Script during it's own OAuth2 flow, and should not be used with this library. The /usercallback endpoint is correct, and the error indicates that it wasn't registered as a callback URL for the client ID you are using. You linked to the Go quickstart for the REST API, which isn't really related to this library. Can you explain what you are trying to accomplish?

**Comment by FrenchBen** [comment]
I'm trying to run an app-scripts from a Go api request.
Looking at the steps above, I followed them all, but it seems that the json file I got didn't have the proper callback. 
Since Google Docs/Sheets API access is limited, I was hoping to create an app-scripts to do the work and interact with it using the script API endpoints.

**Comment by erickoledadevrel** [comment]
This library is for performing OAuth2 authorization in Apps Script itself, while what you want to do is perform OAuth2 authorization in Go, and use it to run an Apps Script. That quickstart you linked to contains the correct steps to follow.

**Comment by FrenchBen** [comment]
Shouldn't the app-scripts tooling provide the proper oauth redirect/tokens ? 
My understanding was that this library was responsible for that functionality and thus at fault for providing the wrong url?

**Comment by erickoledadevrel** [comment]
The Google APIs Client Library for Go provides the OAuth flow, and the library can be used to connect to any Google API (not just Apps Script).
