### ISSUE TITLE
Support for JavaScript

### ISSUE THREAD

**Issue by PatHat** [googlesamples/apps-script-oauth2#34]
Hello.

Can this library be used in JavaScript running in a browser local to my machine, or is only supposed to be used running in the Google Apps Script engine?

I am interested in writing a script for  2-legged OAuth flow (aka, Server to Server authentication) running in an automated fashion in a system external to Google and so do not want any user interaction.  I looked at the library offered by Google Developers (https://developers.google.com/api-client-library/javascript/features/authentication) and it does not seem to support 2-legged OAuth.

Is there a recommended JavaScript library for doing 2-legged OAuth?

**Comment by PatHat** [comment]
Update: I just took at look at the OAuth2.gs code and it looks to be for the Google Apps Script environment only. Is there a regular JavaScript version for this library?

**Comment by erickoledadevrel** [comment]
No, this library is only meant to work within the Google Apps Script environment. For client-side JavaScript, take a look at the jsrsasign library:

https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation

**Comment by PatHat** [comment]
Hello. I'm actually trying to do this on the server-side. Looking for a sample JS code that uses something like a library like jsrsasign to do oauth2 but with no user interaction.
