### ISSUE TITLE
Not possible without attaching it to a document?

### ISSUE THREAD

**Issue by solars** [googlesamples/apps-script-oauth2#36]
Hi there,

This is just a question: If I get this right, it is not possible to create cron-like scripts for Gmail, if I need OAuth2 - as you need to render a link to authorize users and this is only possible in documents.

Is that right? Is there any kind of workaround?

Thanks a lot,
Christoph

**Comment by erickoledadevrel** [comment]
You can create a cron-like script, you just need the person to authorize it one time and then it can run without user intervention after that. The samples in this repo show just that, where they prompt you in the logs to authorize the service the first time.

**Comment by solars** [comment]
Thanks a lot for the pointers! I must have overlooked it
