### ISSUE TITLE
Getting wrong project key

### ISSUE THREAD

**Issue by simonbromberg** [googlesamples/apps-script-oauth2#44]
Using latest version (18) of this oauth2.0 script in Google Sheets for a Fitbit project. No longer gets the correct project key. 

Looking at:
https://github.com/googlesamples/apps-script-oauth2/commit/5b7cf96137c1b2abdb4532f07cdc07b9fded4bec

Is this working as expected for others? Authorization keeps failing and I'm seeing a different project key than expected.

EDIT:
When I run `Logger.log(ScriptApp.getProjectKey());` inside my own project, it logs the project key that I see in the error, but that doesn't match the project key I see in my Project Properties.

**Comment by oshliaer** [comment]
Do you have a code sample to repeat the issue?

**Comment by simonbromberg** [comment]
`Logger.log(ScriptApp.getProjectKey()); `

Compare to project key in File > Project Properties.

**Comment by oshliaer** [comment]
@simonbromberg , oh! I see now. The key in Project Properties doesn't look correct. It's too long.

**Comment by simonbromberg** [comment]
Hm, maybe a bug.

**Comment by simonbromberg** [comment]
Ah, looks like you've already submitted it. Thanks 
https://code.google.com/p/google-apps-script-issues/issues/detail?id=6098&q=Type%3DDefect&colspec=Stars%20Opened%20ID%20Type%20Status%20Summary%20Component%20Owner

**Comment by erickoledadevrel** [comment]
Added a method and instructions to work around the issue. Once fixed in Apps Script, will back out the instructions.
