### ISSUE TITLE
Error getting token for Facebook

### ISSUE THREAD

**Issue by pauladamgordon** [googlesamples/apps-script-oauth2#47]
Hi there,

I've implemented the Facebook sample code in my spreadsheet app, but when copying the code from the logger into the browser all I get is '**Error retrieving token: object Object (line 308, file "Service", project "OAuth2")**'

The code I am copying is 'https://www.facebook.com/dialog/oauth?client_id=698310256946940&response_type=code&redirect_uri=https%3A%2F%2Fscript.google.com%2Fmacros%2Fd%2FMHYm-_trBq8deUlb7Vk0rDfd7JZjerWDk%2Fusercallback&state=ADEpC8zRYuLCWJ9Ou0VgCtRT-xtDcrcnIcJNRz0102_9TQ5Blv4Br0eudbmIHY_cddcrXZ2I077Lk6HP90HNsnA2Iu7I0_IpeKr7waMVQI26BKeikP9sAokfvBaLgilX17NMOVsu2rkY4ATwxD4x2nPo4EflRvkH4Ic-cxpmBx3L1NsiESdfutPLLOYsq8C9v1JCsONh4om3gE_z-kuD5YqIY9A4LXmBufMr4qPH0XUxr568292XW_Z9wfCZxTnCkZTXGMWqoPMdtlNFkUG8M165KlP-tSD7DYbTSjRi7MVAcMh-SnuQe6YPYZ2YMgtrtH6Z3hSFvHk9'

I can't find a reference to this anywhere and I seem to be going in circles.

Thanks in advance,

Paul

**Comment by erickoledadevrel** [comment]
The error was being returned as an object, and since the library wasn't handling that case all it shows in the message was "object Object", which isn't very helpful. I've just released a new version that will show the details of the object, which should help you determine what the underlying error is.

**Comment by pauladamgordon** [comment]
Thanks for that fix.

The error coming back is 'Token response not valid JSON: SyntaxError: Unexpected token: a (line 424, file "Service", project "OAuth2")'

Any ideas?

**Comment by erickoledadevrel** [comment]
That error seems to be coming from a different part of the code, not Facebook. Try using the Facebook sample from scratch and see if you can get that working, and then go from there.
