### ISSUE TITLE
Why can't I get another users OAuth data into my Google Sheet?

### ISSUE THREAD

**Issue by sdooleyFJUHSD** [googlesamples/apps-script-oauth2#49]
@erickoledadevrel Per my previous question (should I ask it here again in full?):

> The library won't work for the scenario where the web app is deployed as the developer. 

So is there a way to depoly it _not_ as the developer, and still get what I'm attempting?
> This is because the state token forged when you get the Authorization URL has the developer's identity, but when the user gits the /usercallback URL is uses their identity.

Is there a way to do what I'm trying to do? (I'm trying to get a users Google account email address into my spreadsheet.)

**Comment by erickoledadevrel** [comment]
There are probably many ways to accomplish what you want, but this library probably isn't the best path. Apps Script provides Session.getActiveUser().getEmail() which works in most contexts and is a much easier path. If that doesn't work, you can explore using [Google Sign-in](https://developers.google.com/identity/sign-in/web/reference).

**Comment by sdooleyFJUHSD** [comment]
Session.getActiveUser().getEmail() gets _my_ email if I deploy it as me, and doesn't return the email if deployed as another user (it would return it to them, but not me). I thought the purpose of this library was to permit me access to their information and bring it back.

Do I misunderstand?

Thank you for the help.
