### ISSUE TITLE
use refresh token to seed new service?

### ISSUE THREAD

**Issue by polvi** [googlesamples/apps-script-oauth2#50]
Hello- if I'm persisting refresh_tokens so that I can connect to a service offline on behalf of the user-- how do I create a service that consumes those? I could not find any docs or anything in the source code to do this. 

Thank you for any help.

**Comment by erickoledadevrel** [comment]
If a refresh_token is present in the response it is automatically stored and used later to refresh the access token. No additional settings or process is required.
