### ISSUE TITLE
Access not granted or expired. (line 352, file "Service", project "OAuth2")

### ISSUE THREAD

**Issue by srbodkhe** [googlesamples/apps-script-oauth2#53]
Access not granted or expired. (line 352, file "Service", project "OAuth2") 
Any solution for this.

**Comment by erickoledadevrel** [comment]
You'll need to provide more information. Try using one of the samples to see if you can get it working.

**Comment by hakanak** [comment]
Hi guy,

mycode: 
`    var service = getOAuthService();
    service.reset();
   // if (service.hasAccess()) {
        var url = 'https://www.googleapis.com/drive/v2/files?pageSize=1';
        var response = UrlFetchApp.fetch(url, {
            headers: {
                Authorization: 'Bearer ' + service.getAccessToken()
            }
        });
        Logger.log(response.getContentText());
    //}`

user  mail : "me"   script working.
user mail : "personelmail@domain.com" script  Access not granted or expired. (line 352, file "Service", project "OAuth2") 

Enable G Suite Domain-wide Delegation : OK

what is the problem?
can you help me?
Thank you in advance.

**Comment by oshliaer** [comment]
Hi @hakanak you'll need to provide more information. As I know this error shows that you don't set enough scopes. Please, show your `OAuth2.createService('srName').setScope(?)`

I think, you have to create a new issue topic.
