### ISSUE TITLE
Clearing after build

### ISSUE THREAD

**Issue by oshliaer** [googlesamples/apps-script-oauth2#55]
After build `npm run-script dist` the next [piece of code](https://github.com/googlesamples/apps-script-oauth2/blob/426bf793ec3760d9150130ba2a25611b72ef5578/src/OAuth2.gs#L64-L69) is not deleted 
```
if (module) {
  module.exports = {
    createService: createService,
    getRedirectUri: getRedirectUri
  };
}
```
I'm not sure that it's the best way to use a undeclared variable. When I forget to remove it I catch `ReferenceError: "module" is not defined. (line 64, file "OAuth2")`

Should I pull a new request?
```
if (typeof module === 'object') {
  module.exports = {
    createService: createService,
    getRedirectUri: getRedirectUri
  };
}
```
Or is there any another way to automate this? I see there is not the code in the [original library](https://script.google.com/d/1B7FSrk5Zi6L1rSxxTDgDEUsPzlukDsi4KGuTMorsTQHhGBzBkMun4iDF/edit?usp=drive_web).

I use the distributive when there is no way to deliver as a library. It is very convenient.

**Comment by erickoledadevrel** [comment]
The dist task uses gulp-expose, which should create a `modules` variables, as is done with the [checked-in version](https://github.com/googlesamples/apps-script-oauth2/blob/master/dist/OAuth2.gs#L2).

That said, your typeof test is the better way to go. If you submit a PR I'll approve it.

**Comment by erickoledadevrel** [comment]
Thanks!
