### ISSUE TITLE
id_token

### ISSUE THREAD

**Issue by guohuang** [googlesamples/apps-script-oauth2#57]
Hi 

Is there a way to return id_token from the service? I need that for token exchange from aws.

Thanks

**Comment by erickoledadevrel** [comment]
The full contents of the token returned at the end of the flow can be accessed via `service.getToken_()`. You can see an example of using this technique in the [Wordpress sample](https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/Wordpress.gs#L10]. If you can provide more details about your AWS use case I may be able to add a sample for that as well.

**Comment by guohuang** [comment]
`service.getToken_().id_token` work like a charm!

Thanks @erickoledadevrel
