### ISSUE TITLE
Getting "Data storage error (line 493, file "Service", project "OAuth2")"

### ISSUE THREAD

**Issue by tomwwillson** [googlesamples/apps-script-oauth2#59]
This error starting appearing this morning on all of my apps using this library.  My users cannot access their database (Google Fusion) that use this library for OAuth access.  

The app was no longer able to get authorized, so I set up the re-authorization process to get a new token and this error appears right after I get the Google "Have Offline Access" with the "Allow" button.

**Comment by daxtari** [comment]
I have exact the same issue when requesting to cloudprint - also urgent please ;-)

**Comment by erickoledadevrel** [comment]
There is currently an outage with the PropertiesService, which this library relies on:

https://code.google.com/p/google-apps-script-issues/issues/detail?id=6856

I'll keep this issue open so others can find it, but the only solution is for the Apps Script team to resolve that outage.

**Comment by tomwwillson** [comment]
It's now working for me.

**Comment by tomwwillson** [comment]
Thanks Eric.  I just started using your library, so I was glad to see that
you were on top of this issue immediately, and that it wasn't rooted in
your code.  I appreciate your support!

Tom Willson
