### ISSUE TITLE
Access not granted or expired. (line 352, file "Service", project "OAuth2")

### ISSUE THREAD

**Issue by antoine-castex** [googlesamples/apps-script-oauth2#60]
Hello

I have 10 script running since 1 year very good

Since friday one of them is dead :  
Access not granted or expired. (line 352, file "Service", project "OAuth2")

i have do nothing ...

i dont how to fix it 

please

thanks

**Comment by oshliaer** [comment]
@antoine-castex Have you tried to reconnect to services? Apparently your tokens are simply overdue. This could happen due to a recent problem with PropertyService #59

**Comment by antoine-castex** [comment]
@oshliaer  thanks you are right but i cant reconnect, when i create new client id and service, i run my function which call getService,  that dont get back to me the log with the url for consent the right

i dont know why

in the past i never have this problem...

you know what im saying ?

**Comment by antoine-castex** [comment]
It's ok , i have successfully re-generated the autorization

it's because i dont use the html page to see the autorization url, i take them in the logger.log and open the url manually.... :+1:

**Comment by oshliaer** [comment]
@antoine-castex It's good!

I'm using `reset` method before re-connect when I run oAuth flow through Logger.

https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/Facebook.gs#L36-L39
