### ISSUE TITLE
Authorization URL fails using Yahoo.gs

### ISSUE THREAD

**Issue by theo-armour** [googlesamples/apps-script-oauth2#61]
Here are the steps I am taking on Win10 running latest Chrome.

Always fails. Ditto similar results with Dropbox.gs.

Can you help?

***

Create a Yahoo app. 

Obtain Client ID (Consumer Key) and Client Secret (Consumer Secret)
* Leave Home Page URL and Callback domain blank

Create Google Apps Script

Load Library Oauth2 version 21 as a resource

Copy and paste the code in the following into Code.gs

 https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/Yahoo.gs

Save and run the 'Run' function

After Run completes successfully,

Open Logger.log

Copy given link and paste into new tab in browser

Yahoo returns: 

> Uh oh
> Looks like something went wrong.
> Please try again later.

Ditto: DropBox with 400 error

**Comment by oshliaer** [comment]
Ok I'd like to provide your throw the example of my app. It works fine for me at this moment.

## YDN Apps
The list of apps https://developer.yahoo.com/apps

### The app settings
* Application Name is filled
* Description(Optional) is empty
* Home Page URL(Optional) is empty
* Callback Domain contains "script.google.com"
* API Permissions
  * Profiles (Social Directory)
    * Read Public

## The script
Identically apps-script-oauth2/samples/Yahoo.gs from https://github.com/googlesamples/apps-script-oauth2

* CLIENT_ID is filled
* CLIENT_SECRET is filled
* `url` variable from `run()` function is ` https://social.yahooapis.com/v1/user/me/profile?format=json`
  * `var url = 'https://social.yahooapis.com/v1/user/me/profile?format=json';`

## What can be done
* Please, try again
* Try `reset()` before the newt call `run()`
* As I know Yahoo had an issue. Maybe they removed it? Try contact with Yahoo Support.

**Comment by theo-armour** [comment]
@oshliaer 

Thank you for the speedy and detailed response.

Success at my end.

Adding the callback domain and API permissions plus changing the user in the URL on line 18 of the script from 'abcdef123' to 'me' seems to have done the trick.

I saw no issues with the Yahoo response. The returned JSON was definitely 'me'.

I'm sure your feedback would b useful to other beginners. Would you like to add these to the README or to the Yahoo.gs file? Or should I put in a pull request?

Again, thank you!

**Comment by oshliaer** [comment]
@theo-armour I've created a new pull request #62 already.

**Comment by erickoledadevrel** [comment]
Merged the change to the sample, sorry for the confusion!
