### ISSUE TITLE
Client is unauthorized to retrieve access tokens using this method

### ISSUE THREAD

**Issue by hakanak** [googlesamples/apps-script-oauth2#64]
Hello,
I have a problem like this:

Error Line: 83 

> 
An unhandled exception of type 'Google.Apis.Auth.OAuth2.Responses.TokenResponseException' occurred in Google.Apis.dll

Additional information: Error:"unauthorized_client", Description:"Client is unauthorized to retrieve access tokens using this method.", Uri:""

Code:
`            //UserCredential credential;
            Dictionary<string, string> dictionary = new Dictionary<string, string>();
            String serviceAccountEmail =
            "xxxxx@xxxxx.iam.gserviceaccount.com";

            var certificate = new X509Certificate2(@"key.p12", "notasecret", X509KeyStorageFlags.Exportable);

   
            ServiceAccountCredential credential = new ServiceAccountCredential(
                new ServiceAccountCredential.Initializer(serviceAccountEmail)
                {
                    
                    User = "personel@mydomain.com",
                    AccessMethod = new BearerToken.AuthorizationHeaderAccessMethod(),
                    DefaultExponentialBackOffPolicy = Google.Apis.Http.ExponentialBackOffPolicy.UnsuccessfulResponse503,
                    
                    Scopes = new[] { GmailService.Scope.MailGoogleCom }
                }.FromCertificate(certificate)
            );

                // Create Gmail API service.
                var gmailService = new GmailService(new BaseClientService.Initializer()
                {
                    HttpClientInitializer = credential,
                    ApplicationName = "MyApp",
                });

                // Define parameters of request.

                var emailListRequest = gmailService.Users.Messages.List("personel@mydomain.com");
                emailListRequest.LabelIds = "INBOX";
                emailListRequest.IncludeSpamTrash = true;
                emailListRequest.Q = "is:unread";
                emailListRequest.MaxResults = 10;

                var emailListResponse = emailListRequest.Execute();

                foreach (var item in emailListResponse.Messages)
                {
                    Console.WriteLine(item.Id);
                }

            Console.Read();`

**Comment by erickoledadevrel** [comment]
It looks like you are using the .NET client library, which is supported here:

https://developers.google.com/api-client-library/dotnet/support
