### ISSUE TITLE
OAuth samples not working.

### ISSUE THREAD

**Issue by Vaibhavdixit02** [googlesamples/apps-script-oauth2#67]
I have been trying to run your samples for various websites and it seems to be not working. I am getting the following error "Cannot read property "parameter" from undefined. (line 270, file "Service", project "OAuth2")". Please look into it. Thank You!

**Comment by erickoledadevrel** [comment]
I'm not able to reproduce that error. Please make sure you are copying the sample code exactly.

**Comment by Vaibhavdixit02** [comment]
Can you please tell me which function did you try to run? I am facing error in the authCallback function. And yes I have copied it exactly.
![screenshot from 2017-05-15 20-02-49](https://cloud.githubusercontent.com/assets/23134958/26062805/8d402f64-39a9-11e7-8561-a36a50af37a4.png)

**Comment by erickoledadevrel** [comment]
The `authCallback` function should not be run directly. It is called automatically when you complete the OAuth approval flow. Instead, just run the function `run`.

**Comment by Vaibhavdixit02** [comment]
Okay. Thanks for the help!
