### ISSUE TITLE
OAuth2 instance for 2 subjects users, domain-wide delegation

### ISSUE THREAD

**Issue by pszafer** [googlesamples/apps-script-oauth2#69]
Hello,

I want to move email from one user mailbox to another user in Google Apps.
I created service account with domain-wide delegation. I can create one instance of OAuth2 service and I can download message for this user.
```
function createOAuthForUser(user){
 return OAuth2.createService("Service Account")
  .setTokenUrl('https://accounts.google.com/o/oauth2/token')
        .setPrivateKey(json.private_key)
        .setIssuer(json.client_email)
        .setSubject(user)
        .setPropertyStore(PropertiesService.getScriptProperties())
        .setScope('https://mail.google.com/');
}
```

for first time I call this function everything is working what I want to do.

```
var service1= createOAuthForUser("mail1@domain.com");
var service2  = createOAuthForUser("mail2@domain.com");
var accessToken1 = service1.getAccessToken();
var accessToken2 = service2.getAccessToken();
```

for second user "mail2@domain.com" I get error 403, email delegation is forbidden for "mail1@domain.com".

Is it my fault somewhere or should I create second service account or is that OAuth2.createService is making only one instance of OAuth2 in one run?

**Comment by erickoledadevrel** [comment]
All tokens are keyed off of the service name. If you want multiple services for multiple users, you need to add the user name (or some other unique ID) to the service name. You can see an example of that here: https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/GoogleServiceAccount.gs#L36
