### ISSUE TITLE
Are there any reasons why Service_.prototype.getToken_ is private?

### ISSUE THREAD

**Issue by vikdet** [googlesamples/apps-script-oauth2#71]
We have sensitive information in token response, but in public service api we have only access to token.access_token via getAccessToken.

**Comment by sqrrrl** [comment]
+1 - would like to see this fully exposed (or a public version that handles the refresh). This would also give access to the id_token if present which is useful for some integrations.

**Comment by oshliaer** [comment]
It seems that the function `Service_.prototype.handleCallback` is terse. Probably, it would be advantageous to use the entire answer in `Service` until the end of the script call. Maybe a callback?

**Comment by erickoledadevrel** [comment]
No good reason why it is private, other than I couldn't find a public use for it at first. Over time I've found that some providers return important custom information in the token response, so some samples use the private method. If someone wants to cut a PR to add a public version I'd be glad to approve it.

**Comment by erickoledadevrel** [comment]
`Service.getToken()` is now public.
