### ISSUE TITLE
Can client ID and secret be the same as the ones for the whole project?

### ISSUE THREAD

**Issue by mihaiaperghis** [googlesamples/apps-script-oauth2#78]
I've been using the OAuth2 library to access the Search Console API, since this API not in the "Advanced Google Services" list. I now notice in my Developer Console that I have two set of credentials, one for the Apps Script project (which is a Google Sheets add-on) and one for the OAuth2 library. 

Would there be any problem to use the Apps Script project credentials for the OAuth2 library? Would that mean that when the user installs the add-on and gets the OAuth window, he/she won't need to do the extra authorization step for the Search Console API?

![credentials search analytics](https://user-images.githubusercontent.com/8843352/30346750-752781ee-9812-11e7-80db-e0cd48b63bbc.png)

Thanks!

**Comment by erickoledadevrel** [comment]
In general we recommend that you don't touch the "Apps Script" client ID, since if it gets deleted or broken there isn't any way to restore it. Even if you did re-use it, you would still need to go through two authorization flows, since the normal Apps Script authorization dialog wouldn't know to ask for the Search Console API scopes.

**Comment by mihaiaperghis** [comment]
Actually I did delete the Apps Script client ID :) Luckily, changing to a new Developer Console project recreates the credentials.

**Comment by erickoledadevrel** [comment]
That will work, but all your existing users will need to re-authorize the script, so it's a last resort.

**Comment by mihaiaperghis** [comment]
Yeah, my mailbox spiked quite a bit :)

Hope that Google either adds more APIs in the Advanced Google services section or allows adding scopes manually to the project to avoid double authorization .
