### ISSUE TITLE
Service fails on 201 status code

### ISSUE THREAD

**Issue by DanWilkerson** [googlesamples/apps-script-oauth2#80]
The supplier of an OAuth API I'm trying to use with the service returns a 201 status code when an access token is created, which causes the Service to fail on line 395, Service.gs:

`if (response.getResponseCode() != 200 || token.error) {`

Not sure what the appropriate fix is here (if any), as this seems to be more the result of a poor interpretation of the W3 status code definition. 

I'm going to drop the Library and load in the source files, then edit my copies for this project, but thought I'd share.

**Comment by DanWilkerson** [comment]
It seems this issue is addressed in the current version of the source code; when will this be coming to the Apps Script Library?

**Comment by oshliaer** [comment]
It is!
[The main library file](https://script.google.com/d/1B7FSrk5Zi6L1rSxxTDgDEUsPzlukDsi4KGuTMorsTQHhGBzBkMun4iDF/edit?usp=drive_web) contains the old code.
I don't know a flow how to publish the new version.

@erickoledadevrel

**Comment by erickoledadevrel** [comment]
Pushed out version 22, which includes the update!

**Comment by DanWilkerson** [comment]
@oshliaer @erickoledadevrel Thank you!
