### ISSUE TITLE
Method Not Allowed: Authorization URL

### ISSUE THREAD

**Issue by Monkeychip** [googlesamples/apps-script-oauth2#86]
I have been able to successfully make an API call to the [Classy.org API](https://developers.classy.org/api-docs/v2/index.html#transaction)  after manually inserting my Authorization Token into Google Scripts, but I continue to run into Errors when trying to retrieve my Authorization Token using the apps-script-oauth2 library. I run the function showSideBar() script copied exactly from the example, but replaced with the Classy.org API information and correct client id and secret (removed for this question).  When I go to the URL returned to authorize, I see this {“error”:“Method not allowed”}. Which according to Classy’s API is a 405 error indicating that “Some REST endpoints only accept a subset of valid REST HTTP verbs. This error is sent when an unsupported verb is requested”.  My App correctly has the OAuth2 Redirect URI set as the one obtained from File-> Project Properties.

Any suggestions would be most appreciated.

```
function getDriveService() {
  return OAuth2.createService('drive')
        .setAuthorizationBaseUrl('https://api.classy.org/oauth2/auth')
        .setTokenUrl('https://api.classy.org/oauth2/auth')  //unsure
        .setClientId('removed')
        .setClientSecret('removed')
        .setCallbackFunction('authCallback')
        .setPropertyStore(PropertiesService.getUserProperties())
        .setScope(''); //optional according to api   
}

function showSidebar(){
  var driveService = getDriveService();
  if(!driveService.hasAccess()){
     var authorizationURL = driveService.getAuthorizationUrl();
        Logger.log(authorizationURL);
  }else{Logger.log("failed at showSidebar function"); }
}
```

**Comment by erickoledadevrel** [comment]
The Classy API appears to use the client_credentials OAuth flow, which isn't yet supported by the API. Please follow issue #82 for updates on when that flow will be available.
