### ISSUE TITLE
Issue with Harvest API

### ISSUE THREAD

**Issue by adrianozappacosta** [googlesamples/apps-script-oauth2#90]
I cover the following issue by calling any request to the Harvest API (https://help.getharvest.com/api-v2/). This request:
///
var response = UrlFetchApp.fetch('https://api.harvestapp.com/v2/clients', {
      headers: {
        Authorization: 'Bearer ' + harvestService.getAccessToken()
      }
    });
///

Results in:

///
Message details
Request failed for https://api.harvestapp.com/v2/clients returned code 401. Truncated server response: {"error":"invalid_token","error_description":"The access token provided is expired, revoked, malformed or invalid for other reasons."} (use muteHttpExceptions option to examine full response)
///

However the authorization works and I do get an access code . Checked with: Logger.log(harvestService.getAccessToken());

Any experience with harvest or idea what the issue can be?

**Comment by erickoledadevrel** [comment]
I've added a sample for the Harvest API here: https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/Harvest.gs

You need to pass the header `Harvest-Account-Id` with each request, otherwise it will fail with that error.
