### ISSUE TITLE
Error 400: Redirect_URI_Mismatch

### ISSUE THREAD

**Issue by chldbwnstm** [googlesamples/apps-script-oauth2#91]
Suddenly from 14/11/15 when I run my Wep app, it gave me this error with the same code that
worked perfectly fine before. 

I changed the redirect URI to https://script.google.com/oauthcallback from 
https://script.google.com/macros/d/{SCRIPT ID}/usercallback on the google api console - credentials
and it started to work again.

Below was the error that I got.

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://script.google.com/oauthcallback, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/xxxxxxxxxxx(deleted for privacy) to update the authorized redirect URIs.

**Comment by erickoledadevrel** [comment]
It sounds like had changed the redirect URI on the existing OAuth client ID that Apps Script uses internally. You should instead create a new client ID and use that with the OAuth2 library.
