### ISSUE TITLE
Dynamic Redirect URI?

### ISSUE THREAD

**Issue by pauladamgordon** [googlesamples/apps-script-oauth2#93]
I'm implementing this library by connecting it to a number of Google Sheets for our clients to use Buffer (https://buffer.com).

The Buffer API requires a specific redirect URI for each app, so I'm finding it tricky to set up as each script authorisation uses a different URI.

Is there any way to set this up in order to implement it once and roll it out across multiple scripts/sheets?

Thanks!

Paul

**Comment by erickoledadevrel** [comment]
If you need to roll out code to multiple sheets the best method is to deploy your code as an add-on. This allows you to use a single redirect URI, as well as push out updates, etc.
