### ISSUE TITLE
what if token endpoint is dynamic ?

### ISSUE THREAD

**Issue by prashantharshi** [googlesamples/apps-script-oauth2#94]
I need to invoke the token url to api_access_point+ouath/token.
The value of api_access_point will be returned by the first /public/oauth url in the query param. That value i need to pass in the token endpoint

**Comment by erickoledadevrel** [comment]
Which API is this?

**Comment by prashantharshi** [comment]
i need to integrate with an oauth provider in which 
1) we will first make an request to public/oauth endpoint which will return me the auth code and api_access_point (i.e kind of a base url for the next /oauth/token endpoint) .Then
2) my token endpoint will be api_access_point + '/oauth/token' . 
how can i get the params recieved from the authorize endpoint(step 1)  so that i can set the correct value of token endpoint
