### ISSUE TITLE
URL does not match any of the prefixes whitelisted for use in the add-on 

### ISSUE THREAD

**Issue by sonha** [googlesamples/apps-script-oauth2#96]
I just tried using gmail add-ons and get the following error: 

"URL ... does not match any of the prefixes whitelisted for use in the add-on."

https://testdomain.com/oauth2/authorize?client_id=23434394431937-ljv054hhvbj4n4jiqor6uss2del0o46n.apps.googleusercontent.com&response_type=code&redirect_uri=https%3A%2F%2Fscript.google.com%2Fmacros%2Fd%2F1nESfiCONMfhFgocEdFjgkvMT9kiOSfVk7aw7Frz5imP4zW_wwK9hr70W%2Fusercallback&state=ADEpC8xifricPRf7_rnIReuX7DutomrafsY5NgQVTrq_8vy1YZfdQTQ8E13NU1FEc35s5p4jxneLL8v87qj13Dj49Fe-1ZVHdTZ0lAoJXMWIp98KOPYwwM2YAO7ho-

Anyone ideas what causes this?

**Comment by erickoledadevrel** [comment]
You'll need to whitelist the URL in the add-ons manifest file: https://developers.google.com/gmail/add-ons/concepts/manifests#whitelisting_urls

**Comment by sonha** [comment]
@erickoledadevrel I whitelisted the URL like that 
"urlFetchWhitelist": [
    "https://gaddon.dev/",
    "https://gaddon.dev/oauth2/"
  ],

"openLinkUrlPrefixes": [
      "https://gaddon.dev/",
      "https://gaddon.dev/oauth2/"
    ],

but its still given me an error.

**Comment by enderahmetyurt** [comment]
@sonha did you solve the problem?

**Comment by deepika537** [comment]
Experiencing the same problem. Trying to open a website on button click. It gives me an error as below eventhough I have whitlisted the url in manifest file. Please let me know How can I fix this issue.
URL (https://login.salesforce.com/) does not match any of the prefixes whitelisted for use in the add-on.
Whitelist:
Original:
- https://mail.google.com/
Effective:
- https://mail.google.com/

**Comment by Ozaiko** [comment]
I have experienced the same problem here, did not find how to solve the issue.

**Comment by lukkyjoe** [comment]
has anybody figured out how to work through this?

**Comment by skakanigit** [comment]
> Experiencing the same problem. Trying to open a website on button click. It gives me an error as below eventhough I have whitlisted the url in manifest file. Please let me know How can I fix this issue.
> URL (https://login.salesforce.com/) does not match any of the prefixes whitelisted for use in the add-on.
> Whitelist:
> Original:
> 
> * https://mail.google.com/
>   Effective:
> * https://mail.google.com/

Hello Deepika,
Have you found the solution this problem? Really appreciate your help on this.

**Comment by skakanigit** [comment]
> I just tried using gmail add-ons and get the following error:
> 
> "URL ... does not match any of the prefixes whitelisted for use in the add-on."
> 
> https://testdomain.com/oauth2/authorize?client_id=23434394431937-ljv054hhvbj4n4jiqor6uss2del0o46n.apps.googleusercontent.com&response_type=code&redirect_uri=https%3A%2F%2Fscript.google.com%2Fmacros%2Fd%2F1nESfiCONMfhFgocEdFjgkvMT9kiOSfVk7aw7Frz5imP4zW_wwK9hr70W%2Fusercallback&state=ADEpC8xifricPRf7_rnIReuX7DutomrafsY5NgQVTrq_8vy1YZfdQTQ8E13NU1FEc35s5p4jxneLL8v87qj13Dj49Fe-1ZVHdTZ0lAoJXMWIp98KOPYwwM2YAO7ho-
> 
> Anyone ideas what causes this?

Hi @sonha ,
Have you found the solution to this problem? Really appreciate your help on this.
